version: "3.9"

networks:
  rag-network:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant/storage:/qdrant/storage
      - ./qdrant/logs:/qdrant/logs
    environment:
      - QDRANT__SERVICE__AUTOFLUSH_INTERVAL=1
    restart: unless-stopped
    networks:
      - rag-network

  vector_db_service:
    image: rag-template_vector_db_service 
    container_name: vector-db-service
    ports:
      - "8003:8003"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - qdrant
    networks:
      - rag-network

  llm_service:
    image: rag-template_llm-service   
    container_name: llm_service
    ports:
      - "8000:8000"
    volumes:
      - ./models/llm:/app/models/llm
      - ./src:/app/src
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - VECTOR_DB_URL=http://vector_db_service:8003
    shm_size: "2g"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    mem_limit: "6g"
    restart: unless-stopped
    depends_on:
      vector_db_service:
        condition: service_started
    networks:
      - rag-network

  triton_client:
    image: rag-template_triton-client   
    container_name: triton_client
    ports:
      - "8002:8002"
    volumes:
      - ./models/reranker:/app/models/reranker
      - ./models/bi_encoder:/app/models/bi_encoder
      - ./src:/app/src
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - VECTOR_DB_URL=http://vector_db_service:8003
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      vector_db_service:
        condition: service_started
    networks:
      - rag-network
